### ISSUE TITLE
v1 arduinoSTM32GENERIC  board support

### ISSUE THREAD

**Issue by vsavic** [xC0000005/M200Toolchain#2]
When I tried to build v1 of M200 I got this error: `Error: This board doesn't support arduinoSTM32GENERIC framework!`

When I tried to build  v2, I didn't got any errors.

Is there maybe some additional requirements for v1 for PlatformIO (v3.6) or maybe some configuration issues in board definition ?

**Comment by vsavic** [comment]
Problem solved, here's few notes how to resolve the issue:
https://gist.github.com/vsavic/af5588deb9d3b709f92714869c10d54f

Thanks @xC0000005 for help.

**Comment by xC0000005** [comment]
I pushed fixes for everything but the timers - that will require me to look at more so I know it's not going to create a problem with the different platforms.
